### ISSUE TITLE
Import bootstrap no longer required

### ISSUE THREAD

**Issue by ScriptedAlchemy** [xolvio/webpack-federation-storybook-design-systems-demo#3]
We patched this in the npm release, i only need bootstrap under specific conditions now

**Comment by lgandecki** [comment]
Fantastic! Tweaked that on the finalVersion branch, along with updating the webpack to fetch the package from the npm.

**Comment by ScriptedAlchemy** [comment]
Bootstrap is very useful for cases where you need synchronous imports. Like hooks 

Require/import from. Not import() 
The main concept is if you intend to import remote code as sync, you **must** have a async import somewhere in the parent. In order for webpack to pause execution and retrieve any additional chunks required (sync remotes for example) will be hoisted to the nearest promise in the tree.
